### ISSUE TITLE
Bug: Fix rendering of certain markdown typesetting(s)

### ISSUE THREAD

**Issue by ohsayan** [terrabasedb/docs#19]
As reported in skytable/skytable#219, the MKSNAP action doesn't render correctly. This is probably because of the way we currently parse configurations in the docbuilder. The solution proposed is however _not_ the way forward but we need a permanent fix for it.

**Comment by zhangyuannie** [comment]
That PR has two components:
- Add the syntax of using `MKSNAP` without argument, which is missing from the docs. You are closing a PR with an issue that address only a subset of problems addressed in the original PR.
- Fixing the bold issue *temporarily*. We all agree that we need a permanent fix, but I think removing the bold while waiting for the docbuilder to be fixed is a sensible way forward, unless we think it's fine to leave the docs in an corrupted state during the time. Remember the docs is the first impression people get from the software, and it is not leaving a good impression currently.

**Comment by ohsayan** [comment]
> That PR has two components:
> - Add the syntax of using `MKSNAP` without argument, which is missing from the docs. You are closing a PR with an issue that address only a subset of problems addressed in the original PR.
> - Fixing the bold issue *temporarily*. We all agree that we need a permanent fix, but I think removing the bold while waiting for the docbuilder to be fixed is a sensible way forward, unless we think it's fine to leave the docs in an corrupted state during the time. Remember the docs is the first impression people get from the software, and it is not leaving a good impression currently.

Oops, I completely missed the syntax bit.

**Comment by ohsayan** [comment]
The bold issues have been fixed.
