### ISSUE TITLE
Instructions cmds need updates

### ISSUE THREAD

**Issue by sim4life** [terrabasedb/docs#63]
In the following instructions page:
https://docs.skytable.io/getting-started/

Following instructions:
```
docker run --name mysky \
    -v ./skytable:/var/lib/skytable \
    -p 2003:2003 \
    skytable/sdb:v0.7.5
```

results in an error:
`docker: Error response from daemon: create ./skytable: "./skytable" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.`

To retain the intended relative path use, kindly change it to:
```
docker run --name mysky \
    -v $PWD/skytable:/var/lib/skytable \
    -p 2003:2003 \
    skytable/sdb:v0.7.5
```

Secondly, executing binary after giving it execute permissions:
`$ skysh -h 127.0.0.1 -p 2003`

results in `zsh` error:
`zsh: command not found: skysh`

Kindly change it to:
`$ ./skysh -h 127.0.0.1 -p 2003`

**Comment by ohsayan** [comment]
+1. Have been thinking about fixing these for a while. Will do
